#配置tomcat服务器相关信息
server:
  port: 8090
  servlet:
    #项目发布路径 一般都是默认值/
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  #配置视图解析器
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/     # /默认代表根目录 src/main/webapp
      suffix: .jsp

#整合MybatisPlus
mybatis-plus:
  #只要定义了别名包 之后的映射类型可以自动的完成拼接.
  type-aliases-package: com.jt.demo.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#打印sql语句
logging:
  level:
    com.jt.demo.mapper: debug

  
  